fix(yeoman-ui): fix lodash import for ESM compatibility
- Change from 'import * as _ from "lodash"' to 'import lodash from "lodash"'
- Update all _.set() calls to lodash.set()
- Fixes 'TypeError: _.set is not a function' in tests